apiVersion: 1

datasources:
  - name: DuckDB Analytics
    type: infinity
    access: proxy
    url: http://duckdb-api:5432
    isDefault: true
    jsonData:
      tlsSkipVerify: true
    editable: true